"""
backend/server.py
FastAPI server running on your Mac.
Receives config from the Vercel UI, runs the bots, streams logs back.
"""

import os
import sys
import json
import asyncio
import subprocess
import threading
from datetime import datetime
from pathlib import Path

from fastapi import FastAPI, BackgroundTasks, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from typing import Optional, List

app = FastAPI(title="ApplyPilot Backend")

# Local backend — allow all origins by default; restrict via ALLOWED_ORIGINS env var in production
_raw_origins = os.getenv("ALLOWED_ORIGINS", "*")
_allowed_origins = ["*"] if _raw_origins == "*" else [o.strip() for o in _raw_origins.split(",")]
app.add_middleware(
    CORSMiddleware,
    allow_origins=_allowed_origins,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── State ─────────────────────────────────────────────────────
BOT_DIR   = Path(os.getenv("BOT_DIR", str(Path.home() / "Desktop/job-hunt-agent")))
LOG_LINES = []          # in-memory log ring buffer
RUNNING   = False
PROCESS   = None

_REDACT_PREFIXES = [str(Path.home()), str(BOT_DIR)]

def _sanitise(line: str) -> str:
    for prefix in _REDACT_PREFIXES:
        line = line.replace(prefix, "~")
    return line


# ── Models ────────────────────────────────────────────────────

class Profile(BaseModel):
    first_name: str
    last_name: str
    email: str
    phone: str
    city: str
    linkedin_url: str = ""
    portfolio_url: str = ""
    github_url: str = ""
    other_url_1: str = ""
    other_url_2: str = ""
    resume_text: str = ""
    target_roles: List[str] = [""]
    target_location: str = "India"
    experience_years: int = 3
    experience_months: int = 0
    current_ctc: str = ""
    expected_ctc: str = ""
    notice_period: str = "30 days"
    min_match_score: int = 70
    max_applications: int = 20
    groq_api_key: str = ""
    sheets_webhook_url: str = ""
    sheets_webhook_secret: str = ""
    google_sheet_url: str = ""
    platforms: List[str] = ["naukri", "linkedin"]

class ScheduleRequest(BaseModel):
    interval: str  # "daily_9am" | "twice_daily" | "weekdays" | "manual"
    platforms: List[str]


# ── Config writer ─────────────────────────────────────────────

def _s(value: str) -> str:
    """JSON-escape a string value for safe embedding inside Python string literals."""
    return json.dumps(str(value))[1:-1]  # json.dumps adds outer quotes; strip them


def write_config(p: Profile):
    """Generate config.py from the profile and write it to BOT_DIR."""
    # Derive remote_only from the location dropdown
    remote_only = p.target_location == "Remote"
    # Job boards need a real city/country string, not "Remote"
    bot_location = "India" if p.target_location == "Remote" else _s(p.target_location)

    # Strip blank role entries so bots don't search with empty keywords
    valid_roles = [r for r in p.target_roles if r.strip()]
    if not valid_roles:
        valid_roles = [""]
    roles_str = json.dumps(valid_roles, indent=8)
    first_role = _s(valid_roles[0]) if valid_roles[0].strip() else ""

    # Format experience as "X years Y months" (or just "X years" if months is 0)
    exp_str = f"{int(p.experience_years)} years"
    if p.experience_months:
        exp_str += f" {int(p.experience_months)} months"

    # Safe representation for the multi-line resume text (no triple-quote injection)
    resume_repr = json.dumps(p.resume_text)  # includes surrounding quotes

    cfg = f'''# Auto-generated by ApplyPilot UI — {datetime.now().strftime("%Y-%m-%d %H:%M")}

PERSONAL = {{
    "first_name":    "{_s(p.first_name)}",
    "last_name":     "{_s(p.last_name)}",
    "email":         "{_s(p.email)}",
    "phone":         "{_s(p.phone)}",
    "location":      "{_s(p.city)}, India",
    "city":          "{_s(p.city)}",
    "state":         "",
    "country":       "India",
    "zip_code":      "",
    "linkedin_url":  "{_s(p.linkedin_url)}",
    "portfolio_url": "{_s(p.portfolio_url)}",
    "github_url":    "{_s(p.github_url)}",
    "other_url_1":   "{_s(p.other_url_1)}",
    "other_url_2":   "{_s(p.other_url_2)}",
    "resume_path":   "resume.pdf",
    "gender":        "",
    "ethnicity":     "",
    "age":           "",
    "veteran":       "No",
    "disability":    "No",
}}

LINKEDIN  = {{"email": "{_s(p.email)}", "password": ""}}
INDEED    = {{"email": "{_s(p.email)}", "password": ""}}
NAUKRI    = {{"email": "{_s(p.email)}", "password": ""}}
GLASSDOOR = {{"email": "{_s(p.email)}", "password": ""}}
FOUNDIT   = {{"email": "{_s(p.email)}", "password": ""}}

SEARCH = {{
    "keywords":         {roles_str},
    "location":         "{bot_location}",
    "remote_only":      {str(remote_only)},
    "easy_apply_only":  True,
    "max_applications": {int(p.max_applications)},
    "experience_level": ["Entry Level", "Associate", "Mid-Senior Level"],
    "date_posted":      "past week",
    "days_since_posted": 7,
    "avoid_companies":  [],
    "avoid_keywords":   ["unpaid", "commission only"],
}}

WORK_AUTH = {{
    "authorized_to_work":  "Yes",
    "require_sponsorship": "No",
    "notice_period":       "{_s(p.notice_period)}",
    "willing_to_relocate": "Yes",
    "remote_work":         "Yes",
}}

EDUCATION = {{
    "highest_level":   "Bachelor's",
    "degree":          "",
    "university":      "",
    "graduation_year": "",
    "gpa":             "",
}}

EXPERIENCE = {{
    "total_years":     "{exp_str}",
    "current_company": "",
    "current_title":   "{first_role}",
    "current_salary":  "{_s(p.current_ctc)}",
    "expected_salary": "{_s(p.expected_ctc)}",
    "currency":        "INR",
}}

SAVED_ANSWERS = {{
    "english":             "Yes",
    "years of experience": "{exp_str}",
    "notice period":       "{_s(p.notice_period)}",
    "notice":              "{_s(p.notice_period)}",
    "salary":              "{_s(p.expected_ctc)}",
    "expected ctc":        "{_s(p.expected_ctc)}",
    "current ctc":         "{_s(p.current_ctc)}",
    "expected salary":     "{_s(p.expected_ctc)}",
    "current salary":      "{_s(p.current_ctc)}",
    "remote":              "Yes",
    "relocate":            "Yes",
    "authorized":          "Yes",
    "visa":                "No",
    "sponsorship":         "No",
    "disability":          "No",
    "veteran":             "No",
    "cover letter":        "Dear Hiring Manager,\\n\\nI am excited to apply for this role. With {exp_str} of experience, I believe I can add immediate value to your team.\\n\\nBest regards,\\n{_s(p.first_name)} {_s(p.last_name)}",
}}

AI = {{
    "enabled":           True,
    "provider":          "groq",
    "groq_api_key":      "{_s(p.groq_api_key)}",
    "gemini_api_key":    "",
    "model":             "llama-3.3-70b-versatile",
    "min_match_score":   {int(p.min_match_score)},
    "cover_letter_tone": "professional but warm",
    "resume_text":       {resume_repr},
}}

SHEETS = {{
    "enabled":          {"True" if p.sheets_webhook_url else "False"},
    "webhook_url":      "{_s(p.sheets_webhook_url)}",
    "sheet_url":        "{_s(p.google_sheet_url)}",
    "webhook_secret":   "{_s(p.sheets_webhook_secret)}",
}}

APIS = {{
    "adzuna": {{"app_id": "", "app_key": "", "country": "in"}},
    "jooble": {{"api_key": ""}},
}}
'''
    config_path = BOT_DIR / "config.py"
    config_path.write_text(cfg)
    return config_path


# ── Log streaming ─────────────────────────────────────────────

def _stream_process(proc):
    global RUNNING
    for line in iter(proc.stdout.readline, ""):
        LOG_LINES.append({"time": datetime.now().strftime("%H:%M:%S"), "msg": _sanitise(line.rstrip())})
        if len(LOG_LINES) > 500:
            LOG_LINES.pop(0)
    proc.wait()
    RUNNING = False
    LOG_LINES.append({"time": datetime.now().strftime("%H:%M:%S"), "msg": "── Bot session ended ──"})


# ── API Endpoints ─────────────────────────────────────────────

@app.get("/health")
def health():
    return {"status": "running", "bot_running": RUNNING}


@app.post("/save-profile")
def save_profile(profile: Profile):
    """Save profile → writes config.py into the bot folder."""
    try:
        path = write_config(profile)
        return {"ok": True, "config_path": str(path)}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/run")
def run_bot(platforms: List[str] = None, background_tasks: BackgroundTasks = None):
    """Start the bot for given platforms."""
    global RUNNING, PROCESS
    if RUNNING:
        return {"ok": False, "message": "Bot is already running"}

    valid = {"linkedin", "naukri", "indeed", "glassdoor", "foundit"}
    selected = [p for p in (platforms or []) if p in valid]

    if selected and len(selected) < len(valid):
        cmd = [sys.executable, str(BOT_DIR / "main.py"), "--platforms", ",".join(selected)]
    else:
        cmd = [sys.executable, str(BOT_DIR / "main.py"), "--auto"]
    RUNNING = True
    LOG_LINES.clear()
    platforms_label = ", ".join(selected) if selected else "all platforms"
    LOG_LINES.append({"time": datetime.now().strftime("%H:%M:%S"), "msg": f"▶ Starting ApplyPilot — {platforms_label}"})

    PROCESS = subprocess.Popen(
        cmd,
        cwd=str(BOT_DIR),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )
    t = threading.Thread(target=_stream_process, args=(PROCESS,), daemon=True)
    t.start()
    return {"ok": True, "message": "Bot started"}


@app.post("/stop")
def stop_bot():
    global RUNNING, PROCESS
    if PROCESS and PROCESS.poll() is None:
        PROCESS.terminate()
        RUNNING = False
        LOG_LINES.append({"time": datetime.now().strftime("%H:%M:%S"), "msg": "⛔ Bot stopped by user"})
        return {"ok": True}
    return {"ok": False, "message": "No bot running"}


@app.get("/logs")
def get_logs():
    return {"logs": LOG_LINES[-100:], "running": RUNNING}


@app.get("/status")
def get_status():
    today_log = BOT_DIR / f"applied_jobs_{datetime.now().strftime('%Y%m%d')}.txt"
    applied = []
    if today_log.exists():
        lines = today_log.read_text().splitlines()
        applied = [l.replace("✅ ", "") for l in lines if l.startswith("✅")]
    return {
        "running":       RUNNING,
        "applied_today": len(applied),
        "applied_jobs":  applied[-20:],
    }


# ── Frontend static files ──────────────────────────────────────

_FRONTEND_DIR = Path(__file__).parent.parent / "frontend" / "dist"

if _FRONTEND_DIR.exists():
    app.mount("/assets", StaticFiles(directory=_FRONTEND_DIR / "assets"), name="assets")

    @app.get("/")
    def serve_index():
        return FileResponse(_FRONTEND_DIR / "index.html")

    @app.get("/{full_path:path}")
    def serve_spa(full_path: str):
        # Serve index.html for any unknown path so the SPA router handles it.
        # API routes defined above take priority because FastAPI matches them first.
        return FileResponse(_FRONTEND_DIR / "index.html")


if __name__ == "__main__":
    import uvicorn
    print(f"\n✅ ApplyPilot running at http://localhost:8000")
    print(f"   Open that URL in your browser to use the app.")
    print(f"   Bot directory: {BOT_DIR}\n")
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=False)
